usethis::use_package("glue")
usethis::use_package("edgeR")
usethis::use_package("fs")
usethis::use_package("FactoMineR")
usethis::use_package("factoextra")
usethis::use_package("ggplot2")
usethis::use_package("RColorBrewer")
usethis::use_package("pheatmap")
# usethis::use_package()
# usethis::use_package()
# usethis::use_package()
